### PR TITLE
Swap to using dnsdock instead of dnsmasq+http proxy

### PR DESCRIPTION
**Pull request by chinthakagodawita**
This is a pretty big change that swaps out dnsmasq and the http proxy for a single [dnsdock](https://github.com/tonistiigi/dnsdock) container running a DNS nameserver.

How this works is by adding a route to the private Docker subnet so that all traffic to 172.0.0.16/16 on the dinghy host is forwarded to *.docker. The dnsdock container is also setup as a nameserver for the .docker TLD using the resolver method that in use by the dnsmasq class.

You're then able to set the `DNSDOCK_ALIAS` environment variable in your docker containers to setup hostnames and the dnsdock container automatically creates DNS entries for them.

This simplifies the stack a bit by replacing two services with one.

Benefits:

* No more dnsmasq (one less service to worry about)
* No more nginx http proxy, one less layer go through to get to your containers - the stack gets closer to what you may run on other environments
* Runs in Docker

PR submitted against the `machine` branch as parts of this depend on the changes there.

### CODE REVIEW

**Comment by codekitchen** [comment]
Thanks for the PR. Running a dns server container instead of dnsmasq is great. I have a couple comments/concerns:

* I actually see having the nginx proxy as a positive. For instance, we plan to implement https://github.com/codekitchen/dinghy/issues/2 pretty soon, doing SSL termination in the nginx proxy so we can seamlessly use https for local development.
* At this point there are dozens of docker-compose.yml files with `VIRTUAL_HOST` configurations in them, I know a lot of people would be in for a nasty surprise if that env var stopped working after a dinghy upgrade. In hindsight I should've used a var named `DINGHY_HOSTNAME` or something. But it'd be nice to maintain backwards compatibility.

**Comment by chinthakagodawita** [comment]
True, some good points.

* nginx is great, the problem I've had with it is that not all my sites may use it (some terminate directly in Apache) and it's another thing to debug when issues happen. 
* Good call re: existing Docker Compose files, hadn't considered backwards compatibility!

Given these, what do you think of this approach:

* Still remove dnsmasq and use dnsdock as the nameserver
* Only add the network route to the docker subnet if you're not running a http proxy. This way you've got the option of passing traffic through the proxy if required

This can be taken a step further in that we remove the 'http proxy' option and just have a single 'virtual host' option with two possibilities: http proxy or dns. This way it's obvious that you need to choose one of the two options.

e.g. `dinghy up --virtualhost=proxy` or `dinghy up --virtualhost=dns` (or similar)

I also like the idea of having a `DINGHY_ALIAS` variable. However, I'm not sure what the best way of implementing it across both the proxy and dnsdock would be, without having to maintain custom builds of both.

**Comment by codekitchen** [comment]
I'm just glancing at the dnsdock README, it looks like it'd take some changes for it to work as the nameserver for the nginx proxy right? Right now it's going to resolve `myapp.docker` to the `myapp` container rather than the proxy container, no matter whether the network route is added or not.

I'm a little hesitant to add a global `--virtualhost` switch, in my experience it'll work fine in isolation but cause confusion for teams who are collaborating, and didn't all select the same global option. Would it be possible to support both side-by-side, and make it a per-container config just based on whether `VIRTUAL_HOST` or `DNSDOCK_ALIAS` is defined?

**Comment by chinthakagodawita** [comment]
> Right now it's going to resolve myapp.docker to the myapp container rather than the proxy container, no matter whether the network route is added or not.

We'd need two ways of bringing up dnsdock:

* **If HTTP proxy:**  
  * Don't add network route
  * Start dnsdock container with `-p 53:53/udp` (or mapped to a custom port if you want)
  * Create /etc/resolver/dnsdock with: `nameserver 192.168.99.100` (or whatever your VM IP is and including the custom port if one is defined)

* **If direct route:**
  * Add network route
  * Start dnsdock container with `-p 172.17.42.1:53:53/udp`
  * Create /etc/resolver/dnsdock with: `nameserver 172.17.42.1`

Because of this, I don't think we'll be able to do the routing on a per-container level depending on the alias variable they set.

**Comment by chinthakagodawita** [comment]
Also, regarding the `--virtualhost` switch, perhaps we could make `--proxy` an alias of `--virtualhost=proxy`?

Also potentially add `--direct-route` (or similar) as an alias of `--virtualhost=dns`.

To maintain backwards-compatibility, perhpas `--proxy` should probably remain turned on by default with some documentation around the second flag?

**Comment by codekitchen** [comment]
Hm I may be missing something, I should just try it, but how would your `If HTTP proxy` sequence work? dnsdock is still going to resolve each container to its individual docker interface, not to the http proxy's.

I'm not so much worried about the switch names, but the binary rift it'd create. For instance, my company has 100+ developers working over dozens of teams. Imagine that one team decides to use the proxy, and one team decides to go direct dns. Suddenly their two local development setups can't both work at the same time with dinghy, you can't successfully bring up both projects in the dinghy setup and use them at the same time. It doesn't seem worth the confusion.

**Comment by chinthakagodawita** [comment]
> dnsdock is still going to resolve each container to its individual docker interface, not to the http proxy's

Ha, yes of course, that's what it's supposed to do. I don't know what I was thinking there! Looks like there isn't a way around using dnsmasq if you need the proxy.

> Suddenly their two local development setups can't both work at the same time with dinghy, you can't successfully bring up both projects in the dinghy setup and use them at the same time. It doesn't seem worth the confusion.

Completely understand. I'm happy for you to just close this PR off in that case, I'll probably just maintain a local fork for us with the direct route option in it :)

**Comment by codekitchen** [comment]
Cool, probably best for now. If I get some time I might dive into getting dnsdock or something like it working for dinghy's use case, since that's way better than running a dns server on the host. Thanks!

**Pull request closed without merging**
