### PR TITLE
Add custom provisioning

### PR DESCRIPTION
**Pull request by ryansch**
This allows me to run a custom provisioning step after machine creation but before we run commands like `mount` that are lost after a reboot.

### CODE REVIEW

**Comment by codekitchen** [comment]
Can you tell me a bit about your use cases for this? I'm wondering if there's a more user-friendly route to accomplish the same thing.

**Comment by ryansch** [comment]
Sure I'm using this to provision rancherOS system services.  Here's the script I'm running: https://github.com/outstand/dash/blob/master/docker/provision-dinghy.sh

**Comment by codekitchen** [comment]
Interesting. I'm a little hesitant on this because it feels like it could be handled just as well from outside of dinghy.

I'm not familiar with all the ins and outs of what you're provisioning, but what's the downside of removing the `sudo reboot` from your provision script, running provision after `dinghy create` finishes and then running `dinghy restart`?

**Comment by ryansch** [comment]
Actually I think you're right.  I'll give that a whirl and report back.

**Comment by ryansch** [comment]
This worked with one caveat.  `/usr/local/bin/docker` doesn't exist for RancherOS.  Docker helpfully creates that as a directory when the http proxy is started the first time.  I have to make sure to remove it and replace it with a symlink before calling `dinghy restart`.  Perhaps we need to make the host docker location configurable/discoverable at some point.

**Comment by ryansch** [comment]
Actually scratch that.  dinghy runs the http proxy container so early that none of my startup stuff can get there in time (the RancherOS console is ephemeral by default).  I'll work on making that configurable instead of reopening this PR.

**Comment by codekitchen** [comment]
I'd be open to changing `dinghy create` to just create the vm, and not start it up, with a message telling people to now run `dinghy up`. The current behavior is really just an artifact of how it used to work when Dinghy ran on top of Vagrant, where create and up were the same thing. Matching the `docker-machine create` behavior seems like a good idea.

**Pull request closed without merging**
