### PR TITLE
VirtualBox extension pack isn't required

### PR DESCRIPTION
**Pull request by mziwisky**
Maybe it was at one point, but I just uninstalled it (for licensing reasons) and everything still works fine.  @codekitchen am I missing something, or can that requirement be removed?

### CODE REVIEW

**Comment by codekitchen** [comment]
I added this note to the README at the same time that we merged the changes to switch from using `boot2docker` to `docker-machine` underneath. If I recall, some `docker-machine` functionality required the extension pack, at least at the time. If it's working without it maybe that's no longer the case. I will do some testing too.

**Comment by mziwisky** [comment]
Cool.  fwiw, I just did some grepping for things like "extension pack" thru the docker-machine git log and didn't find anything juicy.  Also did some googling and didn't turn up any clues.  Virtualbox claims that the extension pack just provides "Support for USB 2.0 and USB 3.0 devices, VirtualBox RDP, disk encryption, NVMe and PXE boot for Intel cards".  I can't think of any way that dinghy would rely on any of that.

**Comment by codekitchen** [comment]
Right on. Honestly, I've been using the xhyve backend exclusively for the last couple years, so I haven't really kept up with Virtualbox changes at all. But I wouldn't be at all surprised if this is no longer necessary, and things seem to be working fine. So 👍

**Comment by mziwisky** [comment]
oooo, should I be on xhyve?  i'm getting a new machine soon, maybe i'll make the switch then.

**Comment by codekitchen** [comment]
I always ran into stability problems with Virtualbox's virtual networking, and xhyve is simpler to set up. Either one should work fine in general though.

**Comment by djbender** [comment]
@mziwisky been really enjoying xhyve.

**Pull request merged**
