### PR TITLE
Implement support for xhyve

### PR DESCRIPTION
**Pull request by fgrehm**
Environment: 

```
$ brew info docker-machine
docker-machine: stable 0.6.0 (bottled), HEAD
Create Docker hosts locally and on cloud providers
https://docs.docker.com/machine
/usr/local/Cellar/docker-machine/0.5.6_1 (5 files, 36.3M)
  Poured from bottle
/usr/local/Cellar/docker-machine/0.6.0 (5 files, 36.8M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/docker-machine.rb
==> Dependencies
Build: go ✘, automake ✘
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

$ brew info xhyve
xhyve: stable 0.2.0, HEAD
xhyve, lightweight OS X virtualization solution based on FreeBSD's bhyve
https://github.com/mist64/xhyve
/usr/local/Cellar/xhyve/0.2.0 (3 files, 224.2K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/xhyve.rb

$ brew info docker-machine-driver-xhyve
docker-machine-driver-xhyve: stable 0.2.2 (bottled), HEAD
Docker Machine driver for xhyve
https://github.com/zchee/docker-machine-driver-xhyve
/usr/local/Cellar/docker-machine-driver-xhyve/0.2.2 (2 files, 12.2M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/docker-machine-driver-xhyve.rb
==> Dependencies
Build: go ✘
Recommended: docker-machine ✔
==> Options
--without-docker-machine
	Build without docker-machine support
--HEAD
	Install HEAD version
```

I gave it a quick try and it seems that things are working fine. I'll continue playing with it throughout the day but it would be awesome to have someone else testing it as well :muscle: 

Cheers!

### CODE REVIEW

**Comment by codekitchen** [comment]
Hey that's cool, thanks. The performance of xhyve still wasn't great yet the last time I checked a few months ago, but I'm watching it with great interest. One thing about the PR, it'd be nice to point people to how to install the xhyve docker-machine driver, either when they try to `create` and don't have it installed or at least in the README.

**Comment by zwily** [comment]
:+1: :smile:

**Comment by fgrehm** [comment]
> The performance of xhyve still wasn't great yet the last time I checked a few months ago, but I'm watching it with great interest

I've been bitten by kernel panics on Linux waaaay to many times in the past because of vbox and I ended up getting spoiled by the stability of LXC back in the days I was using Ubuntu as my main OS (and I've already seen some vbox hiccups on OSX as well :cry: )

But you are right, it seems that vbox has a slightly better performance according to [this blog post](https://thepracticalsysadmin.com/xhyve-vs-vbox-driver-benchmarks-for-docker-machine/) (but I'll continue to try to stay away from vbox as much as I can :grin: )

> One thing about the PR, it'd be nice to point people to how to install the xhyve docker-machine driver, either when they try to create and don't have it installed or at least in the README.

How about the commit above? :smile:

**Comment by codekitchen** [comment]
Cool I think that'll work. I've spun up a new VM using this, going to try it out for a while too.

**Comment by codekitchen** [comment]
If you search `cli.rb` for "virtualbox" you'll find a couple more places where mention of xhyve needs to be added.

**Comment by fgrehm** [comment]
Done! :point_up:

**Comment by codekitchen** [comment]
So far this seems to be working great. I'm good with merging this in.

I wish the xhyve plugin was a bit easier to install, maybe we could get the brew install caveats to at least include a note saying you need to run the two chown/chmod commands. I already had one person get mysterious errors on create because they missed that step.

**Comment by fgrehm** [comment]
Thanks for merging!

> I wish the xhyve plugin was a bit easier to install, maybe we could get the brew install caveats to at least include a note saying you need to run the two chown/chmod commands. I already had one person get mysterious errors on create because they missed that step.

I _think_ the xhyve plugin shows that message already (I remember seeing it before somewhere). Would you prefer to reinforce that for dinghy's caveats?

**Comment by codekitchen** [comment]
Hm he didn't see any message on his machine but possible it was missed. I think it'd be better added to the caveats on https://github.com/Homebrew/homebrew/blob/master/Library/Formula/docker-machine-driver-xhyve.rb

**Comment by fgrehm** [comment]
Hum... I'll try to put up a PR for that :+1: 

I just found out where I saw the message:

screen shot 2016-03-02 at 15 51 01

Not sure if that is being displayed to the user when `dinghy` kicks in (I can't recreate my env right now to find out more about this behavior)

**Comment by zwily** [comment]
No, I didn't see that message when doing the `dinghy create`. I think dinghy must swallow the output?

**Comment by codekitchen** [comment]
Ah, dinghy must be hiding it yeah. I can look into improving that.

**Comment by fgrehm** [comment]
@codekitchen do you want me to open an issue to keep track of that or is it something you might be looking into over the next couple days? :beers:

**Comment by codekitchen** [comment]
Let's open an issue yeah. Thanks

**Pull request merged**
